### PR TITLE
Improved Docs

### PR DESCRIPTION
**Pull request by prathmesh-b**
I have added emoji related to role like 🎥👨‍💻🤳. Hope you like it

### CODE REVIEW

**Comment by prathmesh-b** [comment]
Love to hear feedback

**Comment by Sarveshmrao** [comment]
Awesome can you put some emoji for programmer and freelancer ?

**Comment by prathmesh-b** [comment]
Bro as you requested I have added so please check.😂

**Comment by Sarveshmrao** [comment]
Thanks

**Pull request merged**
